# Generated by Django 3.2.3 on 2021-06-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(choices=[('Airtel', 'Airtel'), ('IDEA', 'IDEA'), ('JIO', 'JIO'), ('BSNL', 'BSNL')], max_length=255)),
                ('plans', models.CharField(choices=[('SMS', 'SMS'), ('DATA', 'DATA'), ('TALK Time', 'TALK TIME')], max_length=255)),
            ],
        ),
    ]
