# Generated by Django 3.2.3 on 2021-06-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0002_operators'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.IntegerField(default=-1.0),
            preserve_default=False,
        ),
    ]
