# Generated by Django 3.2.3 on 2021-06-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0004_auto_20210601_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
