# Generated by Django 3.2.3 on 2021-06-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0006_alter_customuser_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recharge',
            old_name='Operator_name',
            new_name='operator_name',
        ),
    ]
