# Generated by Django 3.2.3 on 2021-06-01 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0007_rename_operator_name_recharge_operator_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operators',
            options={'verbose_name_plural': 'operators'},
        ),
        migrations.AlterModelOptions(
            name='plans',
            options={'verbose_name_plural': 'plans'},
        ),
    ]
