# Generated by Django 3.2.3 on 2021-06-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0008_auto_20210601_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'users'},
        ),
    ]
